App:
  Name: "Iris-demo"
  IP: 127.0.0.1
  Host: localhost
  Port: 8082
  TimeFormat: "2006-01-02 15:04:05"
  LogLevel: 4
  ReleaseMode: "debug"
  Log:
    Path: "./runtime/log/gin.log" #日志文件位置
    MaxSize: 1 #单文件最大容量,单位是MB
    MaxBackups: 3 #最大保留过期文件个数
    MaxAge: 1 #保留过期文件的最大时间间隔,单位是天
    Compress: false #是否需要压缩滚动日志, 使用的 gzip 压缩
    ReportCaller: true
    Level: 4
    PrettyPrint: true
    DisableHTMLEscape: true
  SqlLog:
    Path: "./runtime/sql/access.log" #日志文件位置
    MaxSize: 1 #单文件最大容量,单位是MB
    MaxBackups: 3 #最大保留过期文件个数
    MaxAge: 1 #保留过期文件的最大时间间隔,单位是天
    Compress: false #是否需要压缩滚动日志, 使用的 gzip 压缩
    ReportCaller: false
    Level: 4
    PrettyPrint: false
    DisableHTMLEscape: true
  AccessLog:
    Path: "./runtime/access/sql.log" #日志文件位置
    MaxSize: 1 #单文件最大容量,单位是MB
    MaxBackups: 3 #最大保留过期文件个数
    MaxAge: 1 #保留过期文件的最大时间间隔,单位是天
    Compress: false #是否需要压缩滚动日志, 使用的 gzip 压缩
    ReportCaller: false
    Level: 4
    PrettyPrint: false
    DisableHTMLEscape: true
